extensions:
  aem/cf-editor/1:
    $include: src/aem-cf-editor-1/ext.config.yaml
    runtimeManifest:
      packages:
        book-picker:
          license: Apache-2.0
          actions:
            get-books:
              function: src/aem-cf-editor-1/actions/get-books/index.js
              web: 'yes'
              runtime: nodejs:18
              inputs:
                LOG_LEVEL: debug
                apiKey: $SERVICE_API_KEY
              annotations:
                require-adobe-auth: true
                final: true
            add-sku:
              function: src/aem-cf-editor-1/actions/add-sku/index.js
              web: 'yes'
              runtime: nodejs:18
              inputs:
                LOG_LEVEL: debug
              annotations:
                require-adobe-auth: true
                final: true
